from insights.models import MarketData

def run():
    MarketData.objects.all().delete()

    data = [
        # Python Developer
        {"role": "Python Developer", "city": "Bangalore", "avg_salary": 800000, "min_salary": 500000, "max_salary": 1500000, "demand_score": 92, "top_skills": ["Python", "Django", "FastAPI", "PostgreSQL", "Docker"], "hiring_companies": ["Flipkart", "Razorpay", "Zoho", "Infosys", "TCS"]},
        {"role": "Python Developer", "city": "Chennai", "avg_salary": 650000, "min_salary": 400000, "max_salary": 1200000, "demand_score": 85, "top_skills": ["Python", "Django", "REST API", "MySQL", "Git"], "hiring_companies": ["Zoho", "Freshworks", "TCS", "Wipro", "HCL"]},
        {"role": "Python Developer", "city": "Hyderabad", "avg_salary": 720000, "min_salary": 450000, "max_salary": 1300000, "demand_score": 88, "top_skills": ["Python", "Flask", "FastAPI", "MongoDB", "AWS"], "hiring_companies": ["Amazon", "Microsoft", "Infosys", "Cyient", "Tech Mahindra"]},
        {"role": "Python Developer", "city": "Pune", "avg_salary": 700000, "min_salary": 420000, "max_salary": 1250000, "demand_score": 83, "top_skills": ["Python", "Django", "REST API", "PostgreSQL", "Redis"], "hiring_companies": ["Infosys", "Wipro", "Persistent", "Capgemini", "KPIT"]},
        {"role": "Python Developer", "city": "Mumbai", "avg_salary": 750000, "min_salary": 480000, "max_salary": 1400000, "demand_score": 86, "top_skills": ["Python", "Django", "Pandas", "SQL", "Docker"], "hiring_companies": ["JPMorgan", "Accenture", "TCS", "Cognizant", "Deloitte"]},
        {"role": "Python Developer", "city": "Remote", "avg_salary": 900000, "min_salary": 600000, "max_salary": 1800000, "demand_score": 91, "top_skills": ["Python", "FastAPI", "Docker", "AWS", "CI/CD"], "hiring_companies": ["Razorpay", "Chargebee", "BrowserStack", "Postman", "Freshworks"]},
        {"role": "Python Developer", "city": "Delhi NCR", "avg_salary": 780000, "min_salary": 500000, "max_salary": 1450000, "demand_score": 87, "top_skills": ["Python", "Django", "REST API", "MySQL", "Celery"], "hiring_companies": ["Paytm", "MakeMyTrip", "InMobi", "HCL", "Nagarro"]},
        {"role": "Python Developer", "city": "Coimbatore", "avg_salary": 500000, "min_salary": 300000, "max_salary": 900000, "demand_score": 72, "top_skills": ["Python", "Django", "MySQL", "HTML", "CSS"], "hiring_companies": ["Zoho", "Kovai.co", "LTIMindtree", "Wipro", "TCS"]},
        {"role": "Python Developer", "city": "Salem", "avg_salary": 420000, "min_salary": 250000, "max_salary": 750000, "demand_score": 65, "top_skills": ["Python", "Django", "MySQL", "REST API", "Git"], "hiring_companies": ["Local IT firms", "Zoho", "TCS", "Wipro", "Infosys"]},

        # Full Stack Developer
        {"role": "Full Stack Developer", "city": "Bangalore", "avg_salary": 1000000, "min_salary": 600000, "max_salary": 2000000, "demand_score": 95, "top_skills": ["React", "Node.js", "Python", "PostgreSQL", "AWS"], "hiring_companies": ["Swiggy", "Razorpay", "Freshworks", "Amazon", "Flipkart"]},
        {"role": "Full Stack Developer", "city": "Hyderabad", "avg_salary": 900000, "min_salary": 550000, "max_salary": 1800000, "demand_score": 90, "top_skills": ["React", "Django", "JavaScript", "MongoDB", "Docker"], "hiring_companies": ["Microsoft", "Amazon", "TCS", "Infosys", "Cognizant"]},
        {"role": "Full Stack Developer", "city": "Chennai", "avg_salary": 800000, "min_salary": 500000, "max_salary": 1600000, "demand_score": 87, "top_skills": ["React", "Node.js", "MySQL", "JavaScript", "Redis"], "hiring_companies": ["Zoho", "Freshworks", "Cognizant", "Wipro", "HCL"]},
        {"role": "Full Stack Developer", "city": "Pune", "avg_salary": 850000, "min_salary": 520000, "max_salary": 1700000, "demand_score": 88, "top_skills": ["React", "Spring Boot", "Java", "PostgreSQL", "Docker"], "hiring_companies": ["Infosys", "Persistent", "Capgemini", "KPIT", "Zensar"]},
        {"role": "Full Stack Developer", "city": "Mumbai", "avg_salary": 950000, "min_salary": 580000, "max_salary": 1900000, "demand_score": 92, "top_skills": ["React", "Node.js", "MongoDB", "AWS", "TypeScript"], "hiring_companies": ["Tata Digital", "Reliance Jio", "Accenture", "TCS", "Deloitte"]},
        {"role": "Full Stack Developer", "city": "Remote", "avg_salary": 1100000, "min_salary": 700000, "max_salary": 2200000, "demand_score": 94, "top_skills": ["React", "Node.js", "Python", "Docker", "CI/CD"], "hiring_companies": ["Razorpay", "Chargebee", "BrowserStack", "Postman", "Hasura"]},
        {"role": "Full Stack Developer", "city": "Delhi NCR", "avg_salary": 920000, "min_salary": 560000, "max_salary": 1850000, "demand_score": 91, "top_skills": ["React", "Node.js", "MySQL", "Redis", "AWS"], "hiring_companies": ["Paytm", "MakeMyTrip", "Nykaa", "Zomato", "HCL"]},
        {"role": "Full Stack Developer", "city": "Kochi", "avg_salary": 650000, "min_salary": 400000, "max_salary": 1200000, "demand_score": 78, "top_skills": ["React", "Django", "MySQL", "JavaScript", "Git"], "hiring_companies": ["UST", "IBS Group", "Tata Elxsi", "Wipro", "Infosys"]},

        # React Developer
        {"role": "React Developer", "city": "Bangalore", "avg_salary": 850000, "min_salary": 500000, "max_salary": 1600000, "demand_score": 88, "top_skills": ["React", "JavaScript", "TypeScript", "Redux", "CSS"], "hiring_companies": ["Flipkart", "Swiggy", "Zomato", "Paytm", "PhonePe"]},
        {"role": "React Developer", "city": "Hyderabad", "avg_salary": 780000, "min_salary": 480000, "max_salary": 1500000, "demand_score": 85, "top_skills": ["React", "JavaScript", "Redux", "Node.js", "CSS"], "hiring_companies": ["Microsoft", "Amazon", "Infosys", "TCS", "Cyient"]},
        {"role": "React Developer", "city": "Chennai", "avg_salary": 700000, "min_salary": 430000, "max_salary": 1300000, "demand_score": 82, "top_skills": ["React", "JavaScript", "HTML", "CSS", "TypeScript"], "hiring_companies": ["Zoho", "Freshworks", "Cognizant", "Wipro", "TCS"]},
        {"role": "React Developer", "city": "Pune", "avg_salary": 750000, "min_salary": 460000, "max_salary": 1400000, "demand_score": 83, "top_skills": ["React", "JavaScript", "Redux", "Material UI", "Git"], "hiring_companies": ["Infosys", "Persistent", "Capgemini", "KPIT", "Zensar"]},
        {"role": "React Developer", "city": "Remote", "avg_salary": 950000, "min_salary": 600000, "max_salary": 1900000, "demand_score": 90, "top_skills": ["React", "TypeScript", "Next.js", "Tailwind", "GraphQL"], "hiring_companies": ["Razorpay", "Chargebee", "BrowserStack", "Postman", "Hasura"]},
        {"role": "React Developer", "city": "Mumbai", "avg_salary": 820000, "min_salary": 500000, "max_salary": 1550000, "demand_score": 86, "top_skills": ["React", "JavaScript", "Redux", "Node.js", "MongoDB"], "hiring_companies": ["Tata Digital", "Reliance Jio", "Accenture", "Deloitte", "TCS"]},

        # Django Developer
        {"role": "Django Developer", "city": "Bangalore", "avg_salary": 820000, "min_salary": 500000, "max_salary": 1550000, "demand_score": 86, "top_skills": ["Django", "Python", "REST Framework", "PostgreSQL", "Celery"], "hiring_companies": ["Flipkart", "Razorpay", "Freshworks", "Infosys", "Wipro"]},
        {"role": "Django Developer", "city": "Chennai", "avg_salary": 680000, "min_salary": 420000, "max_salary": 1250000, "demand_score": 82, "top_skills": ["Django", "Python", "MySQL", "REST API", "Redis"], "hiring_companies": ["Zoho", "Freshworks", "TCS", "Cognizant", "HCL"]},
        {"role": "Django Developer", "city": "Hyderabad", "avg_salary": 750000, "min_salary": 460000, "max_salary": 1400000, "demand_score": 84, "top_skills": ["Django", "Python", "PostgreSQL", "Docker", "AWS"], "hiring_companies": ["Amazon", "Microsoft", "Infosys", "Tech Mahindra", "Cyient"]},
        {"role": "Django Developer", "city": "Remote", "avg_salary": 900000, "min_salary": 580000, "max_salary": 1750000, "demand_score": 88, "top_skills": ["Django", "Python", "REST API", "Docker", "CI/CD"], "hiring_companies": ["Chargebee", "Postman", "Hasura", "BrowserStack", "Razorpay"]},

        # Data Analyst
        {"role": "Data Analyst", "city": "Bangalore", "avg_salary": 750000, "min_salary": 450000, "max_salary": 1400000, "demand_score": 82, "top_skills": ["Python", "SQL", "Power BI", "Tableau", "Excel"], "hiring_companies": ["Amazon", "Flipkart", "Accenture", "Deloitte", "KPMG"]},
        {"role": "Data Analyst", "city": "Mumbai", "avg_salary": 700000, "min_salary": 400000, "max_salary": 1300000, "demand_score": 78, "top_skills": ["SQL", "Python", "Excel", "Power BI", "Statistics"], "hiring_companies": ["JPMorgan", "HDFC", "Infosys", "TCS", "Wipro"]},
        {"role": "Data Analyst", "city": "Hyderabad", "avg_salary": 680000, "min_salary": 400000, "max_salary": 1250000, "demand_score": 80, "top_skills": ["SQL", "Python", "Tableau", "Excel", "Statistics"], "hiring_companies": ["Amazon", "Microsoft", "Infosys", "Cognizant", "Deloitte"]},
        {"role": "Data Analyst", "city": "Pune", "avg_salary": 650000, "min_salary": 380000, "max_salary": 1200000, "demand_score": 76, "top_skills": ["SQL", "Excel", "Power BI", "Python", "R"], "hiring_companies": ["Infosys", "Wipro", "Capgemini", "Accenture", "KPMG"]},
        {"role": "Data Analyst", "city": "Chennai", "avg_salary": 620000, "min_salary": 360000, "max_salary": 1150000, "demand_score": 74, "top_skills": ["SQL", "Python", "Excel", "Tableau", "Statistics"], "hiring_companies": ["Zoho", "TCS", "Wipro", "Cognizant", "HCL"]},
        {"role": "Data Analyst", "city": "Delhi NCR", "avg_salary": 720000, "min_salary": 430000, "max_salary": 1350000, "demand_score": 81, "top_skills": ["SQL", "Python", "Power BI", "Excel", "Tableau"], "hiring_companies": ["Paytm", "MakeMyTrip", "Deloitte", "KPMG", "EY"]},

        # DevOps Engineer
        {"role": "DevOps Engineer", "city": "Bangalore", "avg_salary": 1100000, "min_salary": 700000, "max_salary": 2200000, "demand_score": 89, "top_skills": ["Docker", "Kubernetes", "AWS", "CI/CD", "Linux"], "hiring_companies": ["Amazon", "Microsoft", "Google", "Flipkart", "Razorpay"]},
        {"role": "DevOps Engineer", "city": "Hyderabad", "avg_salary": 1000000, "min_salary": 650000, "max_salary": 2000000, "demand_score": 86, "top_skills": ["Docker", "Kubernetes", "Azure", "Jenkins", "Linux"], "hiring_companies": ["Microsoft", "Amazon", "Infosys", "TCS", "Cyient"]},
        {"role": "DevOps Engineer", "city": "Pune", "avg_salary": 950000, "min_salary": 600000, "max_salary": 1900000, "demand_score": 84, "top_skills": ["Docker", "AWS", "Jenkins", "Terraform", "Linux"], "hiring_companies": ["Infosys", "Wipro", "Persistent", "Capgemini", "KPIT"]},
        {"role": "DevOps Engineer", "city": "Chennai", "avg_salary": 900000, "min_salary": 560000, "max_salary": 1750000, "demand_score": 82, "top_skills": ["Docker", "AWS", "CI/CD", "Linux", "Git"], "hiring_companies": ["Zoho", "TCS", "Cognizant", "Wipro", "HCL"]},
        {"role": "DevOps Engineer", "city": "Remote", "avg_salary": 1200000, "min_salary": 800000, "max_salary": 2400000, "demand_score": 91, "top_skills": ["Docker", "Kubernetes", "AWS", "Terraform", "CI/CD"], "hiring_companies": ["Razorpay", "BrowserStack", "Chargebee", "Postman", "Hasura"]},
        {"role": "DevOps Engineer", "city": "Mumbai", "avg_salary": 1050000, "min_salary": 670000, "max_salary": 2100000, "demand_score": 87, "top_skills": ["Docker", "AWS", "Jenkins", "Linux", "Kubernetes"], "hiring_companies": ["Tata Digital", "Reliance Jio", "Accenture", "TCS", "Deloitte"]},

        # Machine Learning Engineer
        {"role": "Machine Learning Engineer", "city": "Bangalore", "avg_salary": 1200000, "min_salary": 800000, "max_salary": 2500000, "demand_score": 91, "top_skills": ["Python", "TensorFlow", "PyTorch", "Scikit-learn", "MLOps"], "hiring_companies": ["Google", "Amazon", "Flipkart", "Swiggy", "Meesho"]},
        {"role": "Machine Learning Engineer", "city": "Hyderabad", "avg_salary": 1100000, "min_salary": 720000, "max_salary": 2200000, "demand_score": 88, "top_skills": ["Python", "TensorFlow", "PyTorch", "NLP", "Computer Vision"], "hiring_companies": ["Microsoft", "Amazon", "Infosys", "TCS", "Cyient"]},
        {"role": "Machine Learning Engineer", "city": "Pune", "avg_salary": 1000000, "min_salary": 650000, "max_salary": 2000000, "demand_score": 85, "top_skills": ["Python", "Scikit-learn", "TensorFlow", "SQL", "MLOps"], "hiring_companies": ["Infosys", "Wipro", "Persistent", "KPIT", "Capgemini"]},
        {"role": "Machine Learning Engineer", "city": "Chennai", "avg_salary": 950000, "min_salary": 620000, "max_salary": 1900000, "demand_score": 83, "top_skills": ["Python", "TensorFlow", "Pandas", "NumPy", "Scikit-learn"], "hiring_companies": ["Zoho", "Freshworks", "TCS", "Wipro", "Cognizant"]},
        {"role": "Machine Learning Engineer", "city": "Remote", "avg_salary": 1400000, "min_salary": 950000, "max_salary": 2800000, "demand_score": 93, "top_skills": ["Python", "PyTorch", "MLOps", "AWS", "Docker"], "hiring_companies": ["Google", "Meesho", "BrowserStack", "Razorpay", "Chargebee"]},
        {"role": "Machine Learning Engineer", "city": "Mumbai", "avg_salary": 1150000, "min_salary": 750000, "max_salary": 2300000, "demand_score": 89, "top_skills": ["Python", "TensorFlow", "SQL", "Azure", "MLOps"], "hiring_companies": ["JPMorgan", "Tata Digital", "Accenture", "Deloitte", "EY"]},

        # Backend Developer
        {"role": "Backend Developer", "city": "Bangalore", "avg_salary": 900000, "min_salary": 560000, "max_salary": 1800000, "demand_score": 88, "top_skills": ["Java", "Spring Boot", "PostgreSQL", "Redis", "Docker"], "hiring_companies": ["Flipkart", "Razorpay", "Amazon", "Infosys", "TCS"]},
        {"role": "Backend Developer", "city": "Pune", "avg_salary": 750000, "min_salary": 450000, "max_salary": 1400000, "demand_score": 83, "top_skills": ["Java", "Spring Boot", "MySQL", "Redis", "Docker"], "hiring_companies": ["Infosys", "Wipro", "Persistent", "Tech Mahindra", "Capgemini"]},
        {"role": "Backend Developer", "city": "Hyderabad", "avg_salary": 850000, "min_salary": 520000, "max_salary": 1650000, "demand_score": 86, "top_skills": ["Java", "Node.js", "PostgreSQL", "AWS", "Docker"], "hiring_companies": ["Microsoft", "Amazon", "Infosys", "Cognizant", "Cyient"]},
        {"role": "Backend Developer", "city": "Chennai", "avg_salary": 720000, "min_salary": 440000, "max_salary": 1350000, "demand_score": 81, "top_skills": ["Java", "Spring Boot", "MySQL", "REST API", "Git"], "hiring_companies": ["Zoho", "TCS", "Wipro", "Cognizant", "HCL"]},
        {"role": "Backend Developer", "city": "Mumbai", "avg_salary": 880000, "min_salary": 540000, "max_salary": 1750000, "demand_score": 87, "top_skills": ["Java", "Node.js", "MongoDB", "Redis", "AWS"], "hiring_companies": ["JPMorgan", "Tata Digital", "Accenture", "Reliance Jio", "TCS"]},
        {"role": "Backend Developer", "city": "Remote", "avg_salary": 1000000, "min_salary": 650000, "max_salary": 2000000, "demand_score": 90, "top_skills": ["Node.js", "Python", "PostgreSQL", "Docker", "CI/CD"], "hiring_companies": ["Razorpay", "Chargebee", "BrowserStack", "Postman", "Freshworks"]},

        # Software Engineer
        {"role": "Software Engineer", "city": "Bangalore", "avg_salary": 950000, "min_salary": 600000, "max_salary": 1900000, "demand_score": 93, "top_skills": ["Python", "Java", "System Design", "SQL", "Git"], "hiring_companies": ["Google", "Amazon", "Flipkart", "Swiggy", "Razorpay"]},
        {"role": "Software Engineer", "city": "Remote", "avg_salary": 900000, "min_salary": 600000, "max_salary": 1800000, "demand_score": 87, "top_skills": ["Python", "JavaScript", "System Design", "SQL", "Git"], "hiring_companies": ["Razorpay", "Freshworks", "Chargebee", "Postman", "BrowserStack"]},
        {"role": "Software Engineer", "city": "Hyderabad", "avg_salary": 880000, "min_salary": 560000, "max_salary": 1750000, "demand_score": 90, "top_skills": ["Java", "Python", "System Design", "SQL", "Docker"], "hiring_companies": ["Microsoft", "Amazon", "Infosys", "TCS", "Cognizant"]},
        {"role": "Software Engineer", "city": "Pune", "avg_salary": 820000, "min_salary": 520000, "max_salary": 1600000, "demand_score": 86, "top_skills": ["Java", "Python", "SQL", "Docker", "Git"], "hiring_companies": ["Infosys", "Wipro", "Persistent", "Capgemini", "KPIT"]},
        {"role": "Software Engineer", "city": "Chennai", "avg_salary": 780000, "min_salary": 490000, "max_salary": 1500000, "demand_score": 84, "top_skills": ["Java", "Python", "MySQL", "REST API", "Git"], "hiring_companies": ["Zoho", "Freshworks", "TCS", "Wipro", "Cognizant"]},
        {"role": "Software Engineer", "city": "Mumbai", "avg_salary": 900000, "min_salary": 570000, "max_salary": 1800000, "demand_score": 89, "top_skills": ["Java", "Python", "System Design", "SQL", "AWS"], "hiring_companies": ["JPMorgan", "Tata Digital", "Accenture", "Deloitte", "TCS"]},
        {"role": "Software Engineer", "city": "Delhi NCR", "avg_salary": 860000, "min_salary": 540000, "max_salary": 1700000, "demand_score": 88, "top_skills": ["Java", "Python", "SQL", "System Design", "Docker"], "hiring_companies": ["Paytm", "MakeMyTrip", "Nykaa", "Zomato", "HCL"]},

        # Frontend Developer
        {"role": "Frontend Developer", "city": "Bangalore", "avg_salary": 800000, "min_salary": 480000, "max_salary": 1550000, "demand_score": 85, "top_skills": ["React", "JavaScript", "HTML", "CSS", "TypeScript"], "hiring_companies": ["Flipkart", "Swiggy", "Zomato", "Razorpay", "PhonePe"]},
        {"role": "Frontend Developer", "city": "Chennai", "avg_salary": 650000, "min_salary": 400000, "max_salary": 1200000, "demand_score": 80, "top_skills": ["React", "JavaScript", "HTML", "CSS", "Tailwind"], "hiring_companies": ["Zoho", "Freshworks", "TCS", "Wipro", "Cognizant"]},
        {"role": "Frontend Developer", "city": "Hyderabad", "avg_salary": 720000, "min_salary": 440000, "max_salary": 1350000, "demand_score": 82, "top_skills": ["React", "JavaScript", "TypeScript", "CSS", "Redux"], "hiring_companies": ["Microsoft", "Amazon", "Infosys", "TCS", "Cyient"]},
        {"role": "Frontend Developer", "city": "Pune", "avg_salary": 700000, "min_salary": 420000, "max_salary": 1300000, "demand_score": 79, "top_skills": ["React", "JavaScript", "HTML", "CSS", "Git"], "hiring_companies": ["Infosys", "Wipro", "Persistent", "Capgemini", "Zensar"]},
        {"role": "Frontend Developer", "city": "Remote", "avg_salary": 900000, "min_salary": 580000, "max_salary": 1750000, "demand_score": 87, "top_skills": ["React", "TypeScript", "Next.js", "Tailwind", "GraphQL"], "hiring_companies": ["Razorpay", "Chargebee", "BrowserStack", "Postman", "Hasura"]},
        {"role": "Frontend Developer", "city": "Mumbai", "avg_salary": 760000, "min_salary": 460000, "max_salary": 1450000, "demand_score": 83, "top_skills": ["React", "JavaScript", "HTML", "CSS", "Redux"], "hiring_companies": ["Tata Digital", "Reliance Jio", "Accenture", "TCS", "Deloitte"]},

        # Java Developer
        {"role": "Java Developer", "city": "Bangalore", "avg_salary": 900000, "min_salary": 550000, "max_salary": 1800000, "demand_score": 87, "top_skills": ["Java", "Spring Boot", "Hibernate", "MySQL", "REST API"], "hiring_companies": ["Infosys", "TCS", "Wipro", "Cognizant", "Accenture"]},
        {"role": "Java Developer", "city": "Hyderabad", "avg_salary": 820000, "min_salary": 500000, "max_salary": 1600000, "demand_score": 84, "top_skills": ["Java", "Spring Boot", "Microservices", "Docker", "AWS"], "hiring_companies": ["Microsoft", "Amazon", "Infosys", "Cognizant", "Tech Mahindra"]},
        {"role": "Java Developer", "city": "Pune", "avg_salary": 800000, "min_salary": 490000, "max_salary": 1550000, "demand_score": 83, "top_skills": ["Java", "Spring Boot", "Hibernate", "MySQL", "REST API"], "hiring_companies": ["Infosys", "Wipro", "Persistent", "KPIT", "Capgemini"]},
        {"role": "Java Developer", "city": "Chennai", "avg_salary": 720000, "min_salary": 440000, "max_salary": 1350000, "demand_score": 80, "top_skills": ["Java", "Spring Boot", "MySQL", "REST API", "Git"], "hiring_companies": ["Zoho", "TCS", "Wipro", "Cognizant", "HCL"]},
        {"role": "Java Developer", "city": "Mumbai", "avg_salary": 860000, "min_salary": 530000, "max_salary": 1700000, "demand_score": 85, "top_skills": ["Java", "Spring Boot", "Microservices", "MongoDB", "AWS"], "hiring_companies": ["JPMorgan", "HDFC", "Accenture", "TCS", "Deloitte"]},
        {"role": "Java Developer", "city": "Delhi NCR", "avg_salary": 840000, "min_salary": 520000, "max_salary": 1650000, "demand_score": 84, "top_skills": ["Java", "Spring Boot", "Hibernate", "MySQL", "Docker"], "hiring_companies": ["Paytm", "HCL", "Nagarro", "Genpact", "Accenture"]},

        # QA Engineer
        {"role": "QA Engineer", "city": "Bangalore", "avg_salary": 700000, "min_salary": 420000, "max_salary": 1300000, "demand_score": 78, "top_skills": ["Selenium", "Python", "Manual Testing", "API Testing", "Postman"], "hiring_companies": ["Flipkart", "Amazon", "Infosys", "TCS", "Wipro"]},
        {"role": "QA Engineer", "city": "Hyderabad", "avg_salary": 650000, "min_salary": 390000, "max_salary": 1200000, "demand_score": 75, "top_skills": ["Selenium", "Java", "TestNG", "API Testing", "JIRA"], "hiring_companies": ["Microsoft", "Amazon", "Infosys", "Cognizant", "Tech Mahindra"]},
        {"role": "QA Engineer", "city": "Pune", "avg_salary": 620000, "min_salary": 370000, "max_salary": 1150000, "demand_score": 73, "top_skills": ["Selenium", "Java", "Manual Testing", "Postman", "JIRA"], "hiring_companies": ["Infosys", "Wipro", "Persistent", "Capgemini", "KPIT"]},
        {"role": "QA Engineer", "city": "Chennai", "avg_salary": 580000, "min_salary": 350000, "max_salary": 1100000, "demand_score": 71, "top_skills": ["Selenium", "Python", "Manual Testing", "API Testing", "Git"], "hiring_companies": ["Zoho", "TCS", "Wipro", "Cognizant", "HCL"]},

        # Associate Software Engineer (Fresher)
        {"role": "Associate Software Engineer", "city": "Bangalore", "avg_salary": 500000, "min_salary": 350000, "max_salary": 800000, "demand_score": 82, "top_skills": ["Python/Java", "DSA", "SQL", "Git", "Problem Solving"], "hiring_companies": ["TCS", "Infosys", "Wipro", "Cognizant", "HCL"]},
        {"role": "Associate Software Engineer", "city": "Chennai", "avg_salary": 420000, "min_salary": 300000, "max_salary": 700000, "demand_score": 78, "top_skills": ["Python/Java", "DSA", "SQL", "Git", "Communication"], "hiring_companies": ["TCS", "Infosys", "Wipro", "Zoho", "HCL"]},
        {"role": "Associate Software Engineer", "city": "Hyderabad", "avg_salary": 480000, "min_salary": 330000, "max_salary": 780000, "demand_score": 80, "top_skills": ["Python/Java", "DSA", "MySQL", "Git", "Problem Solving"], "hiring_companies": ["TCS", "Infosys", "Wipro", "Cognizant", "Tech Mahindra"]},
        {"role": "Associate Software Engineer", "city": "Pune", "avg_salary": 460000, "min_salary": 320000, "max_salary": 750000, "demand_score": 77, "top_skills": ["Python/Java", "DSA", "SQL", "Git", "OOPs"], "hiring_companies": ["Infosys", "Wipro", "Capgemini", "Persistent", "KPIT"]},
        {"role": "Associate Software Engineer", "city": "Coimbatore", "avg_salary": 350000, "min_salary": 250000, "max_salary": 600000, "demand_score": 70, "top_skills": ["Python/Java", "DSA", "MySQL", "Git", "Communication"], "hiring_companies": ["Zoho", "Kovai.co", "TCS", "Wipro", "LTIMindtree"]},
        {"role": "Associate Software Engineer", "city": "Salem", "avg_salary": 300000, "min_salary": 200000, "max_salary": 500000, "demand_score": 65, "top_skills": ["Python/Java", "DSA", "MySQL", "Git", "Problem Solving"], "hiring_companies": ["TCS", "Wipro", "Infosys", "Local IT firms", "Zoho"]},

        # Computer Vision Engineer
        {"role": "Computer Vision Engineer", "city": "Bangalore", "avg_salary": 1100000, "min_salary": 700000, "max_salary": 2200000, "demand_score": 85, "top_skills": ["Python", "OpenCV", "YOLOv8", "TensorFlow", "Deep Learning"], "hiring_companies": ["Google", "Amazon", "Ola", "Swiggy", "Niramai"]},
        {"role": "Computer Vision Engineer", "city": "Hyderabad", "avg_salary": 1000000, "min_salary": 650000, "max_salary": 2000000, "demand_score": 82, "top_skills": ["Python", "OpenCV", "PyTorch", "YOLO", "Computer Vision"], "hiring_companies": ["Microsoft", "Amazon", "Infosys", "Cyient", "NVIDIA"]},
        {"role": "Computer Vision Engineer", "city": "Remote", "avg_salary": 1250000, "min_salary": 850000, "max_salary": 2500000, "demand_score": 88, "top_skills": ["Python", "OpenCV", "YOLOv8", "TensorFlow", "MLOps"], "hiring_companies": ["Google", "Meesho", "Razorpay", "BrowserStack", "Niramai"]},

        # IoT Engineer
        {"role": "IoT Engineer", "city": "Bangalore", "avg_salary": 850000, "min_salary": 520000, "max_salary": 1650000, "demand_score": 78, "top_skills": ["Python", "C/C++", "ESP32", "MQTT", "AWS IoT"], "hiring_companies": ["Bosch", "Siemens", "Infosys", "TCS", "L&T Technology"]},
        {"role": "IoT Engineer", "city": "Pune", "avg_salary": 780000, "min_salary": 480000, "max_salary": 1500000, "demand_score": 75, "top_skills": ["Python", "C/C++", "Arduino", "Raspberry Pi", "MQTT"], "hiring_companies": ["Bosch", "KPIT", "Persistent", "Tata Technologies", "L&T Technology"]},
        {"role": "IoT Engineer", "city": "Chennai", "avg_salary": 700000, "min_salary": 430000, "max_salary": 1350000, "demand_score": 72, "top_skills": ["Python", "C/C++", "ESP32", "Node-RED", "MQTT"], "hiring_companies": ["Zoho", "Tata Elxsi", "TCS", "Wipro", "L&T Technology"]},

        # Cloud Engineer
        {"role": "Cloud Engineer", "city": "Bangalore", "avg_salary": 1050000, "min_salary": 650000, "max_salary": 2100000, "demand_score": 90, "top_skills": ["AWS", "Azure", "GCP", "Terraform", "Docker"], "hiring_companies": ["Amazon", "Microsoft", "Google", "Infosys", "Wipro"]},
        {"role": "Cloud Engineer", "city": "Hyderabad", "avg_salary": 950000, "min_salary": 600000, "max_salary": 1900000, "demand_score": 87, "top_skills": ["AWS", "Azure", "Docker", "Kubernetes", "Terraform"], "hiring_companies": ["Microsoft", "Amazon", "Infosys", "Tech Mahindra", "Cognizant"]},
        {"role": "Cloud Engineer", "city": "Pune", "avg_salary": 900000, "min_salary": 570000, "max_salary": 1800000, "demand_score": 85, "top_skills": ["AWS", "Azure", "Docker", "CI/CD", "Linux"], "hiring_companies": ["Infosys", "Wipro", "Persistent", "Capgemini", "KPIT"]},
        {"role": "Cloud Engineer", "city": "Remote", "avg_salary": 1150000, "min_salary": 750000, "max_salary": 2300000, "demand_score": 92, "top_skills": ["AWS", "GCP", "Kubernetes", "Terraform", "CI/CD"], "hiring_companies": ["Razorpay", "Chargebee", "BrowserStack", "Postman", "Hasura"]},

        # Business Analyst
        {"role": "Business Analyst", "city": "Bangalore", "avg_salary": 800000, "min_salary": 500000, "max_salary": 1500000, "demand_score": 80, "top_skills": ["SQL", "Excel", "Power BI", "JIRA", "Agile"], "hiring_companies": ["Flipkart", "Amazon", "Accenture", "Deloitte", "KPMG"]},
        {"role": "Business Analyst", "city": "Mumbai", "avg_salary": 750000, "min_salary": 460000, "max_salary": 1400000, "demand_score": 78, "top_skills": ["SQL", "Excel", "Tableau", "JIRA", "Communication"], "hiring_companies": ["JPMorgan", "HDFC", "Accenture", "TCS", "Deloitte"]},
        {"role": "Business Analyst", "city": "Delhi NCR", "avg_salary": 770000, "min_salary": 480000, "max_salary": 1450000, "demand_score": 79, "top_skills": ["SQL", "Excel", "Power BI", "JIRA", "Agile"], "hiring_companies": ["Paytm", "HCL", "Genpact", "Accenture", "EY"]},

        # UI/UX Designer
        {"role": "UI/UX Designer", "city": "Bangalore", "avg_salary": 780000, "min_salary": 480000, "max_salary": 1500000, "demand_score": 82, "top_skills": ["Figma", "Adobe XD", "Sketch", "Prototyping", "User Research"], "hiring_companies": ["Flipkart", "Swiggy", "Razorpay", "Freshworks", "Meesho"]},
        {"role": "UI/UX Designer", "city": "Mumbai", "avg_salary": 720000, "min_salary": 440000, "max_salary": 1380000, "demand_score": 78, "top_skills": ["Figma", "Adobe XD", "Prototyping", "User Research", "CSS"], "hiring_companies": ["Tata Digital", "Reliance Jio", "Accenture", "TCS", "Deloitte"]},
        {"role": "UI/UX Designer", "city": "Remote", "avg_salary": 880000, "min_salary": 560000, "max_salary": 1700000, "demand_score": 85, "top_skills": ["Figma", "Prototyping", "User Research", "Design Systems", "CSS"], "hiring_companies": ["Razorpay", "BrowserStack", "Chargebee", "Postman", "Freshworks"]},
    ]

    for item in data:
        MarketData.objects.create(**item)

    print(f"{len(data)} market data records created successfully!")