# Generated by Django 6.0.6 on 2026-06-16 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('avg_salary', models.IntegerField(default=0)),
                ('min_salary', models.IntegerField(default=0)),
                ('max_salary', models.IntegerField(default=0)),
                ('demand_score', models.IntegerField(default=0)),
                ('top_skills', models.JSONField(default=list)),
                ('hiring_companies', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
